In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
dataset = pd.read_csv('https://raw.githubusercontent.com/bio-chem-info/python_course/refs/heads/main/preprocess_data.csv')

In [ ]:
dataset

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
a= dataset.tail(2).T

In [ ]:
a

                 8        9
Country    Germany   France
Age           50.0     37.0
Salary     83000.0  67000.0
Purchased       No      Yes

In [ ]:
#dataset.head(2)- koliko prvih ćelija ispisati tu je 2, tail- zadnji redovi, zagrada nam govori koliko toga ide

In [ ]:
dataset.head(5)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [ ]:
x = dataset.iloc[:, :-1]
y= dataset.iloc[:, -1]

In [ ]:
#indexiranje!!!!, dahvaćanje podataka

In [ ]:
x

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [ ]:
x.describe()

             Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [ ]:
#stat podaci, par bitnijih

In [ ]:
x.isna().sum()

Country    0
Age        1
Salary     1
dtype: int64

In [ ]:
dataset

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
x

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [ ]:
x.isna().sum()

Country    0
Age        1
Salary     1
dtype: int64

In [ ]:
#koliko missing values imamo, prebroji ih, isna- filtriranje missing values, sum ih zbraja, kako su operacije ide ()

In [ ]:
#taking care of missing data

In [ ]:
x

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
#nije u memoriji
x.fillna(0)

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      0.0
5   France  35.0  58000.0
6    Spain   0.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
#punimo nan sa 0

In [ ]:
#x.fillna(0, InPlace=True), ostaje u memoriji, inače ne

In [ ]:
#stvaranje novog objekta, ne želimo da nam se x mijenja pa radimo novi x1 koji ima 0

x1= x.fillna(0)
x1

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      0.0
5   France  35.0  58000.0
6    Spain   0.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
#nemamo vrijednost punimo sa medijanom ili srednjom vrijednosti

In [ ]:
x

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
x.fillna(0, inplace=True)

In [ ]:
x

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      0.0
5   France  35.0  58000.0
6    Spain   0.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
x.fillna(-99)
#najprije loadamo stari x, onaj na početku, i onda se on puni sa -99, x.fillna(-99)

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0    -99.0
5   France  35.0  58000.0
6    Spain -99.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
x

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
#nije sačuvano u memoriju, nismo stavili inplace=True

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer (missing_values=np.nan,
                         strategy= 'median')
imputer.fit(x[['Age', 'Salary']])
imputer.statistics_
#fit znači naučiti nešto,
#imputer mijenja nan vrijednosti sa medijanon, u ovom slučaju, tu mora naučiti medijanje, to ga fit uči
#indexiranje [], [[]], kada je više stvari, prva je za indexiranje, druga za listu

array([3.8e+01, 6.1e+04])

In [ ]:
imputer

SimpleImputer(strategy='median')

In [ ]:
x[['Age', 'Salary']].median()

Age          38.0
Salary    61000.0
dtype: float64

In [ ]:
#fit, uči, nauči obrazac

In [ ]:
x

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
x_imputer = imputer.transform(x[['Age', 'Salary']])
#transform nam u ovom slučaju radi isto što i fill, mijenja nan sa medijanom

In [ ]:
imputer

SimpleImputer(strategy='median')

In [ ]:
x_imputer

array([[4.4e+01, 7.2e+04],
       [2.7e+01, 4.8e+04],
       [3.0e+01, 5.4e+04],
       [3.8e+01, 6.1e+04],
       [4.0e+01, 6.1e+04],
       [3.5e+01, 5.8e+04],
       [3.8e+01, 5.2e+04],
       [4.8e+01, 7.9e+04],
       [5.0e+01, 8.3e+04],
       [3.7e+01, 6.7e+04]])

In [ ]:
x_imp = pd.DataFrame(x_imputer,
                     columns= ['Age', 'Salary'],
                     index= x.index)

#tri argumenta koja ima: data, ime columns, i index

In [ ]:
x_imp

    Age   Salary
0  44.0  72000.0
1  27.0  48000.0
2  30.0  54000.0
3  38.0  61000.0
4  40.0  61000.0
5  35.0  58000.0
6  38.0  52000.0
7  48.0  79000.0
8  50.0  83000.0
9  37.0  67000.0

In [ ]:
x_imp.median()

Age          38.0
Salary    61000.0
dtype: float64

In [ ]:
x

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
x.fillna(-666, inplace=True)

In [ ]:
imputer= SimpleImputer( missing_values=-666,
                       strategy= 'mean')

In [ ]:
imputer

SimpleImputer(missing_values=-666)

In [ ]:
imputer.fit(x[['Age', 'Salary']])
imputer.statistics_

array([3.87777778e+01, 6.37777778e+04])

In [ ]:
x[['Age', 'Salary']].mean()

Age         -31.7
Salary    57333.4
dtype: float64

In [ ]:
x_imputer = imputer.transform(x[['Age', 'Salary']])

In [ ]:
x_imputer

array([[4.40000000e+01, 7.20000000e+04],
       [2.70000000e+01, 4.80000000e+04],
       [3.00000000e+01, 5.40000000e+04],
       [3.80000000e+01, 6.10000000e+04],
       [4.00000000e+01, 6.37777778e+04],
       [3.50000000e+01, 5.80000000e+04],
       [3.87777778e+01, 5.20000000e+04],
       [4.80000000e+01, 7.90000000e+04],
       [5.00000000e+01, 8.30000000e+04],
       [3.70000000e+01, 6.70000000e+04]])

In [ ]:
x_imp = pd.DataFrame(x_imputer,
                     columns= ['Age', 'Salary'],
                     index= x.index)

In [ ]:
x_imp

         Age        Salary
0  44.000000  72000.000000
1  27.000000  48000.000000
2  30.000000  54000.000000
3  38.000000  61000.000000
4  40.000000  63777.777778
5  35.000000  58000.000000
6  38.777778  52000.000000
7  48.000000  79000.000000
8  50.000000  83000.000000
9  37.000000  67000.000000

In [ ]:
#encoding the independant var

In [ ]:
x

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
#get dummies iz pd, matrica, stupci koji želimo u numeričke i drop fist- miče jednu, ne trebaju nam 3 inf

In [ ]:
x_encoded = pd.get_dummies(x, columns= ['Country'], drop_first=True )
x_encoded

    Age   Salary  Country_Germany  Country_Spain
0  44.0  72000.0            False          False
1  27.0  48000.0            False           True
2  30.0  54000.0             True          False
3  38.0  61000.0            False           True
4  40.0      NaN             True          False
5  35.0  58000.0            False          False
6   NaN  52000.0            False           True
7  48.0  79000.0            False          False
8  50.0  83000.0             True          False
9  37.0  67000.0            False          False

In [ ]:
x_encoded = x_encoded.replace({True:1, False:0})
x_encoded

/tmp/ipython-input-3823664502.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  x_encoded = x_encoded.replace({True:1, False:0})

    Age   Salary  Country_Germany  Country_Spain
0  44.0  72000.0                0              0
1  27.0  48000.0                0              1
2  30.0  54000.0                1              0
3  38.0  61000.0                0              1
4  40.0      NaN                1              0
5  35.0  58000.0                0              0
6   NaN  52000.0                0              1
7  48.0  79000.0                0              0
8  50.0  83000.0                1              0
9  37.0  67000.0                0              0

In [ ]:
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [ ]:
y_encoded = x_encoded.replace({True:1, False:0})
y_encoded
# korisitmo {} jer pišemo što mijenjamo sa čime, to nam je knjižnica, library

    Age   Salary  Country_Germany  Country_Spain
0  44.0  72000.0                0              0
1  27.0  48000.0                0              1
2  30.0  54000.0                1              0
3  38.0  61000.0                0              1
4  40.0      NaN                1              0
5  35.0  58000.0                0              0
6   NaN  52000.0                0              1
7  48.0  79000.0                0              0
8  50.0  83000.0                1              0
9  37.0  67000.0                0              0

In [ ]:
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [ ]:
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [ ]:
y_encoded = pd.get_dummies(y)
y_encoded

      No    Yes
0   True  False
1  False   True
2   True  False
3   True  False
4  False   True
5  False   True
6   True  False
7  False   True
8   True  False
9  False   True

In [ ]:
y_encoded = y_encoded.replace({True:1, False:0})
y_encoded

/tmp/ipython-input-767361250.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y_encoded = y_encoded.replace({True:1, False:0})

   No  Yes
0   1    0
1   0    1
2   1    0
3   1    0
4   0    1
5   0    1
6   1    0
7   0    1
8   1    0
9   0    1

In [ ]:
y1= y_encoded['No']
y1.name = 'Purchase'
y1

0    1
1    0
2    1
3    1
4    0
5    0
6    1
7    0
8    1
9    0
Name: Purchase, dtype: int64

In [ ]:
y1 = y.replace({'Yes:1', 'No:0'})
y1

/tmp/ipython-input-1527472584.py:1: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  y1 = y.replace({'Yes:1', 'No:0'})

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [ ]:
#splitting the dataset into the traning set and test set

In [ ]:
#modeli regresije(npr tjedan trudnuće) i klasifikacija(da/ne)

In [ ]:
#nasumično odvajanje, to je bitno, fita se na model i onda se provjerava sa validacijom(poznatim inf)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(x_encoded,
                                                   y_encoded,
                                                   test_size=0.25,
                                                   random_state=1)

In [ ]:
print(X_train)

    Age   Salary  Country_Germany  Country_Spain
4  40.0      NaN                1              0
0  44.0  72000.0                0              0
3  38.0  61000.0                0              1
1  27.0  48000.0                0              1
7  48.0  79000.0                0              0
8  50.0  83000.0                1              0
5  35.0  58000.0                0              0

In [ ]:
print(X_test)

    Age   Salary  Country_Germany  Country_Spain
2  30.0  54000.0                1              0
9  37.0  67000.0                0              0
6   NaN  52000.0                0              1

In [ ]:
#feature scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_sc= sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)
sc
#train ga nauči, inače to sam ne zna

StandardScaler()

In [ ]:
sc.scale_

array([7.34291273e+00, 1.22667120e+04, 4.51753951e-01, 4.51753951e-01])

In [ ]:
sc.mean_

array([4.02857143e+01, 6.68333333e+04, 2.85714286e-01, 2.85714286e-01])

In [ ]:
X_train_sc = pd.DataFrame(X_train_sc, columns=X_train.columns, index=X_train.index)

In [ ]:
X_train.std()

Age                    7.931252
Salary             13437.509690
Country_Germany        0.487950
Country_Spain          0.487950
dtype: float64

In [ ]:
X_train.var()

Age                6.290476e+01
Salary             1.805667e+08
Country_Germany    2.380952e-01
Country_Spain      2.380952e-01
dtype: float64

In [ ]:
#dvije formule za var, sa n ili sa n-1, n-1 korisitmo ako ne znamo kolika je točno populacija, tako kompenziramo

In [ ]:
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.fit_transform(X_test)

In [ ]:
X_train_sc = pd.DataFrame (X_train_sc, columns=X_train.columns, index=X_train.index)

In [ ]:
X_train_sc

        Age    Salary  Country_Germany  Country_Spain
4 -0.038910       NaN         1.581139      -0.632456
0  0.505833  0.421194        -0.632456      -0.632456
3 -0.311282 -0.475542        -0.632456       1.581139
1 -1.809325 -1.535320        -0.632456       1.581139
7  1.050576  0.991844        -0.632456      -0.632456
8  1.322947  1.317930         1.581139      -0.632456
5 -0.719839 -0.720106        -0.632456      -0.632456

In [ ]:
X_train

    Age   Salary  Country_Germany  Country_Spain
4  40.0      NaN                1              0
0  44.0  72000.0                0              0
3  38.0  61000.0                0              1
1  27.0  48000.0                0              1
7  48.0  79000.0                0              0
8  50.0  83000.0                1              0
5  35.0  58000.0                0              0

In [ ]:
X_train_sc.describe()

                Age        Salary  Country_Germany  Country_Spain
count  7.000000e+00  6.000000e+00     7.000000e+00   7.000000e+00
mean   1.427430e-16  4.070818e-16     3.172066e-17   3.172066e-17
std    1.080123e+00  1.095445e+00     1.080123e+00   1.080123e+00
min   -1.809325e+00 -1.535320e+00    -6.324555e-01  -6.324555e-01
25%   -5.155603e-01 -6.589650e-01    -6.324555e-01  -6.324555e-01
50%   -3.891021e-02 -2.717381e-02    -6.324555e-01  -6.324555e-01
75%    7.782042e-01  8.491816e-01     4.743416e-01   4.743416e-01
max    1.322947e+00  1.317930e+00     1.581139e+00   1.581139e+00

In [ ]:
X_train.describe()

             Age        Salary  Country_Germany  Country_Spain
count   7.000000      6.000000         7.000000       7.000000
mean   40.285714  66833.333333         0.285714       0.285714
std     7.931252  13437.509690         0.487950       0.487950
min    27.000000  48000.000000         0.000000       0.000000
25%    36.500000  58750.000000         0.000000       0.000000
50%    40.000000  66500.000000         0.000000       0.000000
75%    46.000000  77250.000000         0.500000       0.500000
max    50.000000  83000.000000         1.000000       1.000000

In [ ]:
#skaliranje 3 std gore i dolje, mean je oko 0, skaliramo tako da nam bude uniformnije

In [ ]:

from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
X_train_sc= sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)
sc

MinMaxScaler()

In [ ]:
X_train_sc = pd.DataFrame(X_train_sc, columns=X_train.columns, index=X_train.index)

In [ ]:
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.fit_transform(X_test)

In [ ]:
X_train_sc = pd.DataFrame (X_train_sc, columns=X_train.columns, index=X_train.index)

In [ ]:
X_train_sc

        Age    Salary  Country_Germany  Country_Spain
4  0.565217       NaN              1.0            0.0
0  0.739130  0.685714              0.0            0.0
3  0.478261  0.371429              0.0            1.0
1  0.000000  0.000000              0.0            1.0
7  0.913043  0.885714              0.0            0.0
8  1.000000  1.000000              1.0            0.0
5  0.347826  0.285714              0.0            0.0

In [ ]:
X_train

    Age   Salary  Country_Germany  Country_Spain
4  40.0      NaN                1              0
0  44.0  72000.0                0              0
3  38.0  61000.0                0              1
1  27.0  48000.0                0              1
7  48.0  79000.0                0              0
8  50.0  83000.0                1              0
5  35.0  58000.0                0              0

In [ ]:
X_train_sc.describe()

            Age    Salary  Country_Germany  Country_Spain
count  7.000000  6.000000         7.000000       7.000000
mean   0.577640  0.538095         0.285714       0.285714
std    0.344837  0.383929         0.487950       0.487950
min    0.000000  0.000000         0.000000       0.000000
25%    0.413043  0.307143         0.000000       0.000000
50%    0.565217  0.528571         0.000000       0.000000
75%    0.826087  0.835714         0.500000       0.500000
max    1.000000  1.000000         1.000000       1.000000

In [ ]:
X_train.describe()

             Age        Salary  Country_Germany  Country_Spain
count   7.000000      6.000000         7.000000       7.000000
mean   40.285714  66833.333333         0.285714       0.285714
std     7.931252  13437.509690         0.487950       0.487950
min    27.000000  48000.000000         0.000000       0.000000
25%    36.500000  58750.000000         0.000000       0.000000
50%    40.000000  66500.000000         0.000000       0.000000
75%    46.000000  77250.000000         0.500000       0.500000
max    50.000000  83000.000000         1.000000       1.000000